name: Deno 🦕

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [0.x, 0.30.x, 0.1]

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/github-script@0.4.0
      with:
        github-token: ${{ github.token }}
        script: |
          const releases = (await github.repos.listReleases({
            owner: 'denoland',
            repo: 'deno'
          })).data
          const tags = releases.map(x => x.tag_name)
          console.log('Deno Releases:')
          console.log(tags)
    
    - uses: joshmgross/setup-deno@master
      with:
        deno-version: 0.x
    - run: |
        deno --version
        deno run https://deno.land/std/examples/welcome.ts
